In [9]:
import  pandas as pd

In [10]:
url="https://raw.githubusercontent.com/tarikkranda/pi_datasets/main/country_vaccination_stats.csv"
data = pd.read_csv(url)

In [11]:
data

,country,date,daily_vaccinations,vaccines
0,Argentina,12/29/2020,NaN,Sputnik V
1,Argentina,12/30/2020,15656.0,Sputnik V
2,Argentina,12/31/2020,15656.0,Sputnik V
3,Argentina,1/1/2021,11070.0,Sputnik V
4,Argentina,1/2/2021,8776.0,Sputnik V
...,...,...,...,...
1497,Wales,1/20/2021,11105.0,"Oxford/AstraZeneca, Pfizer/BioNTech"
1498,Wales,1/21/2021,12318.0,"Oxford/AstraZeneca, Pfizer/BioNTech"
1499,Wales,1/22/2021,15148.0,"Oxford/AstraZeneca, Pfizer/BioNTech"
1500,Wales,1/23/2021,17371.0,"Oxford/AstraZeneca, Pfizer/BioNTech"
1501,Wales,1/24/2021,17063.0,"Oxford/AstraZeneca, Pfizer/BioNTech"

In [12]:
data['daily_vaccinations'] = data['daily_vaccinations'].fillna(0)

In [13]:
data

,country,date,daily_vaccinations,vaccines
0,Argentina,12/29/2020,0.0,Sputnik V
1,Argentina,12/30/2020,15656.0,Sputnik V
2,Argentina,12/31/2020,15656.0,Sputnik V
3,Argentina,1/1/2021,11070.0,Sputnik V
4,Argentina,1/2/2021,8776.0,Sputnik V
...,...,...,...,...
1497,Wales,1/20/2021,11105.0,"Oxford/AstraZeneca, Pfizer/BioNTech"
1498,Wales,1/21/2021,12318.0,"Oxford/AstraZeneca, Pfizer/BioNTech"
1499,Wales,1/22/2021,15148.0,"Oxford/AstraZeneca, Pfizer/BioNTech"
1500,Wales,1/23/2021,17371.0,"Oxford/AstraZeneca, Pfizer/BioNTech"
1501,Wales,1/24/2021,17063.0,"Oxford/AstraZeneca, Pfizer/BioNTech"

In [87]:
max_values = data.sort_values(by = ['daily_vaccinations'],ascending=False)[:3]

In [88]:
max_values['country']

1458    United States
1457    United States
1456    United States
Name: country, dtype: object

In [90]:
sum_val = data[(data["date"] == '1/6/2021')]

In [93]:
sum_val['daily_vaccinations'].sum()

1466568.0

In [101]:
import pandasql as ps
url="https://raw.githubusercontent.com/tarikkranda/pi_datasets/main/country_vaccination_stats.csv"
data_sql = pd.read_csv(url)

In [102]:
mysql = ps.sqldf('select * from data_sql', locals())

In [103]:
mysql

,country,date,daily_vaccinations,vaccines
0,Argentina,12/29/2020,NaN,Sputnik V
1,Argentina,12/30/2020,15656.0,Sputnik V
2,Argentina,12/31/2020,15656.0,Sputnik V
3,Argentina,1/1/2021,11070.0,Sputnik V
4,Argentina,1/2/2021,8776.0,Sputnik V
...,...,...,...,...
1497,Wales,1/20/2021,11105.0,"Oxford/AstraZeneca, Pfizer/BioNTech"
1498,Wales,1/21/2021,12318.0,"Oxford/AstraZeneca, Pfizer/BioNTech"
1499,Wales,1/22/2021,15148.0,"Oxford/AstraZeneca, Pfizer/BioNTech"
1500,Wales,1/23/2021,17371.0,"Oxford/AstraZeneca, Pfizer/BioNTech"
1501,Wales,1/24/2021,17063.0,"Oxford/AstraZeneca, Pfizer/BioNTech"

In [104]:
query = ps.sqldf('select * from data_sql where daily_vaccinations IS NULL ', locals())

In [105]:
query

,country,date,daily_vaccinations,vaccines
0,Argentina,12/29/2020,None,Sputnik V
1,Austria,1/5/2021,None,Pfizer/BioNTech
2,Bahrain,12/23/2020,None,"Pfizer/BioNTech, Sinopharm"
3,Belgium,12/28/2020,None,Pfizer/BioNTech
4,Brazil,1/16/2021,None,Sinovac
5,Bulgaria,12/29/2020,None,"Moderna, Pfizer/BioNTech"
6,Canada,12/14/2020,None,"Moderna, Pfizer/BioNTech"
7,Chile,12/24/2020,None,Pfizer/BioNTech
8,China,12/15/2020,None,"CNBG, Sinovac"
9,Costa Rica,12/24/2020,None,Pfizer/BioNTech
10,Croatia,12/30/2020,None,Pfizer/BioNTech
11,Cyprus,1/6/2021,None,Pfizer/BioNTech
12,Czechia,12/27/2020,None,"Moderna, Pfizer/BioNTech"
13,Denmark,12/27/2020,None,"Moderna, Pfizer/BioNTech"
14,Ecuador,1/21/2021,None,Pfizer/BioNTech
15,England,12/20/2020,None,"Oxford/AstraZeneca, Pfizer/BioNTech"
16,Estonia,12/28/2020,None,Pfizer/BioNTech
17,Finland,12/31/2020,None,Pfizer/BioNTech
18,France,1/4/2021,None,Pfizer/BioNTech
19,Germany,12/27/2020,None,"Moderna, Pfizer/BioNTech"
20,Gibraltar,1/10/2021,None,Pfizer/BioNTech
21,Greece,12/28/2020,None,Pfizer/BioNTech
22,Hungary,12/28/2020,None,Pfizer/BioNTech
23,Iceland,12/30/2020,None,"Moderna, Pfizer/BioNTech"
24,India,1/15/2021,None,"Covaxin, Covishield"
25,Indonesia,1/12/2021,None,Sinovac
26,Ireland,12/31/2020,None,Pfizer/BioNTech
27,Isle of Man,1/21/2021,None,Pfizer/BioNTech
28,Israel,12/19/2020,None,"Moderna, Pfizer/BioNTech"
29,Italy,12/27/2020,None,Pfizer/BioNTech
30,Kuwait,12/28/2020,None,Pfizer/BioNTech
31,Latvia,12/28/2020,None,Pfizer/BioNTech
32,Lithuania,12/25/2020,None,"Moderna, Pfizer/BioNTech"
33,Luxembourg,12/30/2020,None,Pfizer/BioNTech
34,Malta,12/28/2020,None,Pfizer/BioNTech
35,Mexico,12/24/2020,None,Pfizer/BioNTech
36,Netherlands,1/6/2021,None,"Moderna, Pfizer/BioNTech"
37,Northern Ireland,12/13/2020,None,"Oxford/AstraZeneca, Pfizer/BioNTech"
38,Norway,12/27/2020,None,Pfizer/BioNTech
39,Oman,12/28/2020,None,Pfizer/BioNTech
40,Panama,1/19/2021,None,Pfizer/BioNTech
41,Poland,12/28/2020,None,Pfizer/BioNTech
42,Portugal,12/27/2020,None,Pfizer/BioNTech
43,Romania,12/28/2020,None,Pfizer/BioNTech
44,Russia,12/15/2020,None,Sputnik V
45,Saudi Arabia,1/6/2021,None,Pfizer/BioNTech
46,Scotland,12/13/2020,None,"Oxford/AstraZeneca, Pfizer/BioNTech"
47,Serbia,1/8/2021,None,"Pfizer/BioNTech, Sinopharm, Sputnik V"
48,Seychelles,1/9/2021,None,Sinopharm
49,Singapore,1/11/2021,None,Pfizer/BioNTech
50,Slovakia,1/4/2021,None,Pfizer/BioNTech
51,Slovenia,1/3/2021,None,Pfizer/BioNTech
52,Spain,1/4/2021,None,"Moderna, Pfizer/BioNTech"
53,Sweden,12/27/2020,None,Pfizer/BioNTech
54,Switzerland,12/23/2020,None,Pfizer/BioNTech
55,Turkey,1/13/2021,None,Sinovac
56,United Arab Emirates,1/5/2021,None,"Pfizer/BioNTech, Sinopharm"
57,United Kingdom,12/20/2020,None,"Oxford/AstraZeneca, Pfizer/BioNTech"
58,United States,12/20/2020,None,"Moderna, Pfizer/BioNTech"
59,Wales,12/13/2020,None,"Oxford/AstraZeneca, Pfizer/BioNTech"

In [108]:
query1 = ps.sqldf('select COALESCE(daily_vaccinations, 0 ) from data_sql  ', locals())

In [109]:
query1

      COALESCE(daily_vaccinations, 0 )
0                                  0.0
1                              15656.0
2                              15656.0
3                              11070.0
4                               8776.0
...                                ...
1497                           11105.0
1498                           12318.0
1499                           15148.0
1500                           17371.0
1501                           17063.0

[1502 rows x 1 columns]

In [124]:
query12 = ps.sqldf('SELECT country FROM data_sql ORDER BY daily_vaccinations LIMIT 1 OFFSET (SELECT COUNT(*) FROM data_sql) / 2', locals())

In [125]:
query12

  country
0  Greece